"""added card_tables to schema

Revision ID: 157b122d1363
Revises: 483182fb2897
Create Date: 2024-09-13 13:12:32.157097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '157b122d1363'
down_revision = '483182fb2897'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_tables',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pot_amount', sa.Integer(), nullable=False),
    sa.Column('min_stake', sa.Integer(), nullable=False),
    sa.Column('max_stake', sa.Integer(), nullable=False),
    sa.Column('hole_cards', sa.String(length=280), nullable=True),
    sa.Column('game_type', sa.String(length=280), nullable=False),
    sa.Column('is_girls_only', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card_tables')
    # ### end Alembic commands ###
