"""added playing table to schema

Revision ID: 26f591377840
Revises: 157b122d1363
Create Date: 2024-09-13 13:36:00.403284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26f591377840'
down_revision = '157b122d1363'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playing',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['card_tables.id'], ),
    sa.PrimaryKeyConstraint('player_id', 'table_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playing')
    # ### end Alembic commands ###
