"""first migration added players table

Revision ID: 483182fb2897
Revises: 
Create Date: 2024-09-13 13:09:55.189452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '483182fb2897'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=280), nullable=False),
    sa.Column('email', sa.String(length=280), nullable=False),
    sa.Column('password', sa.String(length=280), nullable=False),
    sa.Column('sex', sa.String(length=280), nullable=False),
    sa.Column('hand', sa.String(length=280), nullable=True),
    sa.Column('bankroll', sa.Integer(), nullable=True),
    sa.Column('table_stakes', sa.Integer(), nullable=True),
    sa.Column('current_bet', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('players')
    # ### end Alembic commands ###
