"""added dealers table to schema

Revision ID: 66dd4a1a7d5a
Revises: 26f591377840
Create Date: 2024-09-13 13:40:41.658395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66dd4a1a7d5a'
down_revision = '26f591377840'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dealers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=280), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dealers')
    # ### end Alembic commands ###
